class Strings {
  static const Map<String, Map<String, String>> _all = {
    'en': {
      'nav.analyze': 'Analyze',
      'nav.history': 'History',
      'nav.settings': 'Settings',
      'onboarding.title1': 'Analyze Instagram Accounts',
      'onboarding.desc1': 'Enter any Instagram username and get detailed analytics, follower insights, and growth metrics instantly.',
      'onboarding.title2': 'Track Your Growth',
      'onboarding.desc2': 'Monitor follower growth, engagement rates, and track who follows you back with beautiful interactive charts.',
      'onboarding.title3': 'Stay Organized',
      'onboarding.desc3': 'Save your favorite accounts, track changes over time, and sync your data across all your devices.',
      'onboarding.skip': 'Skip',
      'onboarding.get_started': 'Get Started',
      'onboarding.next': 'Next',
      'search.title': 'Analyze Profile',
      'search.subtitle': 'Enter an Instagram username to get insights',
      'search.hint': 'Enter username...',
      'search.button': 'Analyze',
      'search.no_saved': 'No saved accounts yet',
      'search.view_follow': 'View Follow Analysis',
      'search.view_dashboard': 'View Dashboard',
      'search.search_another': 'Search Another',
      'search.saved_accounts': 'Saved Accounts',
      'profile.verified': 'Verified',
      'profile.public': 'Public',
      'profile.private': 'Private',
      'profile.private_hint': 'Private account — followers and media are not available',
      'profile.posts': 'Posts',
      'profile.followers': 'Followers',
      'profile.following': 'Following',
      'history.title': 'History',
      'history.subtitle': 'Previously analyzed profiles',
      'history.empty': 'No search history yet',
      'history.empty_hint': 'Analyze a profile to see it here',
      'history.profiles': 'profiles',
      'history.clear': 'Clear All',
      'follow.not_following_back': 'Not Following You Back',
      'follow.not_followed': 'You Don\'t Follow Back',
      'follow.mutual': 'Mutual Followers',
      'follow.empty': 'No users in this category',
      'follow.more': '+ %s more',
      'follow.show_less': 'Show less',

      'settings.title': 'Settings',
      'settings.dark_mode': 'Dark Mode',
      'settings.dark_hint': 'Toggle dark theme',
      'settings.language': 'Language',
      'settings.lang_en': 'English',
      'settings.lang_ru': 'Русский',
      'settings.notifications': 'Notifications',
      'settings.notif_hint': 'Push notifications',
      'settings.cache': 'Clear Cache',
      'settings.cache_hint': 'Free up storage space',
      'settings.privacy': 'Privacy',
      'settings.privacy_hint': 'Manage your data',
      'settings.about': 'About',
      'settings.about_hint': 'Version 1.0.0',
      'about.description': 'InstaCheck helps you analyze Instagram profiles, track follower growth, and gain valuable insights about your social media presence.',
      'about.made_by': 'Made with ❤️ by InstaCheck Team',
      'common.error': 'Error',
      'common.loading': 'Loading...',
      'common.retry': 'Retry',
      'error.user_not_found': 'User not found',
      'error.challenge_required': 'Instagram requires verification. Open Instagram on your phone.',
      'error.rate_limited': 'Too many requests. Please wait a moment.',
      'error.session_expired': 'Session expired. Please try again.',
      'error.server_error': 'Server error. Please try again later.',
      'error.connection_error': 'Network error. Check your connection.',
      'error.two_factor_required': '2FA required. Log in on Instagram first.',
      'error.login_failed': 'Login failed. Please try again later.',
      'error.private_account': 'This account is private.',
      'common.done': 'Done',
      'common.cancel': 'Cancel',
      'common.delete': 'Delete',
      'history.delete_confirm_title': 'Clear history',
      'history.delete_confirm_message': 'Delete all search history?',
      'history.delete_selected_confirm': 'Delete selected profiles?',
      'history.delete_selected': 'Delete selected',
      'history.cancel': 'Cancel',
      'stats.followers': 'Followers',
      'stats.following': 'Following',
      'stats.posts': 'Posts',
      'stats.engagement': 'Engagement',
      'stats.avg_likes': 'Avg Likes',
      'stats.avg_comments': 'Avg Comments',
      'stats.profile_views': 'Profile Views',
      'stats.story_views': 'Story Views',
    },
    'ru': {
      'nav.analyze': 'Анализ',
      'nav.history': 'История',
      'nav.settings': 'Настройки',
      'onboarding.title1': 'Анализируйте аккаунты Instagram',
      'onboarding.desc1': 'Введите любой username и получите детальную аналитику, данные о подписчиках и метрики роста мгновенно.',
      'onboarding.title2': 'Отслеживайте рост',
      'onboarding.desc2': 'Следите за ростом подписчиков, уровнем вовлечённости и кто подписан на вас взаимно с красивыми графиками.',
      'onboarding.title3': 'Оставайтесь организованным',
      'onboarding.desc3': 'Сохраняйте любимые аккаунты, отслеживайте изменения и синхронизируйте данные на всех устройствах.',
      'onboarding.skip': 'Пропустить',
      'onboarding.get_started': 'Начать',
      'onboarding.next': 'Далее',
      'search.title': 'Анализ профиля',
      'search.subtitle': 'Введите username Instagram для анализа',
      'search.hint': 'Введите username...',
      'search.button': 'Анализировать',
      'search.no_saved': 'Нет сохранённых аккаунтов',
      'search.view_follow': 'Анализ подписчиков',
      'search.view_dashboard': 'Смотреть статистику',
      'search.search_another': 'Поиск другого',
      'search.saved_accounts': 'Сохранённые',
      'profile.verified': 'Подтверждён',
      'profile.public': 'Публичный',
      'profile.private': 'Закрытый',
      'profile.private_hint': 'Закрытый аккаунт — подписчики и медиа недоступны',
      'profile.posts': 'Публикации',
      'profile.followers': 'Подписчиков',
      'profile.following': 'Подписок',
      'history.title': 'История',
      'history.subtitle': 'Ранее проанализированные профили',
      'history.empty': 'История поиска пуста',
      'history.empty_hint': 'Проанализируйте профиль, чтобы он появился здесь',
      'history.profiles': 'профилей',
      'history.clear': 'Очистить',
      'follow.not_following_back': 'Не подписаны в ответ',
      'follow.not_followed': 'Вы не подписаны',
      'follow.mutual': 'Взаимные подписки',
      'follow.empty': 'Нет пользователей в этой категории',
      'follow.more': 'Ещё %s',
      'follow.show_less': 'Свернуть',
      'settings.title': 'Настройки',
      'settings.dark_mode': 'Тёмная тема',
      'settings.dark_hint': 'Включить тёмную тему',
      'settings.language': 'Язык',
      'settings.lang_en': 'English',
      'settings.lang_ru': 'Русский',
      'settings.notifications': 'Уведомления',
      'settings.notif_hint': 'Push-уведомления',
      'settings.cache': 'Очистить кэш',
      'settings.cache_hint': 'Освободить место',
      'settings.privacy': 'Конфиденциальность',
      'settings.privacy_hint': 'Управление данными',
      'settings.about': 'О приложении',
      'settings.about_hint': 'Версия 1.0.0',
      'about.description': 'InstaCheck помогает анализировать профили Instagram, отслеживать рост подписчиков и получать ценную информацию о вашем присутствии в соцсетях.',
      'about.made_by': 'Сделано с ❤️ командой InstaCheck',
      'common.error': 'Ошибка',
      'common.loading': 'Загрузка...',
      'common.retry': 'Повторить',
      'error.user_not_found': 'Пользователь не найден',
      'error.challenge_required': 'Instagram требует подтверждения. Откройте Instagram на телефоне.',
      'error.rate_limited': 'Слишком много запросов. Подождите немного.',
      'error.session_expired': 'Сессия истекла. Попробуйте снова.',
      'error.server_error': 'Ошибка сервера. Попробуйте позже.',
      'error.connection_error': 'Ошибка сети. Проверьте подключение.',
      'error.two_factor_required': 'Требуется 2FA. Сначала войдите в Instagram.',
      'error.login_failed': 'Ошибка входа. Попробуйте позже.',
      'error.private_account': 'Этот аккаунт закрыт.',
      'common.done': 'Готово',
      'common.cancel': 'Отмена',
      'common.delete': 'Удалить',
      'history.delete_confirm_title': 'Очистить историю',
      'history.delete_confirm_message': 'Удалить всю историю поиска?',
      'history.delete_selected_confirm': 'Удалить выбранные профили?',
      'history.delete_selected': 'Удалить выбранные',
      'history.cancel': 'Отмена',
      'stats.followers': 'Подписчиков',
      'stats.following': 'Подписок',
      'stats.posts': 'Посты',
      'stats.engagement': 'Вовлечённость',
      'stats.avg_likes': 'Ср. лайки',
      'stats.avg_comments': 'Ср. комментарии',
      'stats.profile_views': 'Просмотры профиля',
      'stats.story_views': 'Просмотры сторис',
    },
  };

  static String tr(String key, {String lang = 'en'}) {
    return _all[lang]?[key] ?? _all['en']?[key] ?? key;
  }

  static String trWithArgs(String key, String arg, {String lang = 'en'}) {
    final template = tr(key, lang: lang);
    return template.replaceAll('%s', arg);
  }
}
